// Generated by CoffeeScript 1.6.3
var crypto, digest, md5, _;

crypto = require('crypto');

_ = require('underscore');

md5 = function(string) {
  var hash;
  hash = crypto.createHash('md5');
  hash.update(string);
  return hash.digest('hex');
};

module.exports = digest = {
  parseChallenge: function(challengeString) {
    var obj;
    obj = {};
    _.each(challengeString.substring(7).split(/,\s+/), function(part) {
      var key, valueInQuotes, _ref;
      _ref = part.split('='), key = _ref[0], valueInQuotes = _ref[1];
      return obj[key] = valueInQuotes.replace(/"/g, '');
    });
    return obj;
  },
  renderResponse: function(challenge, username, password, path) {
    var h1, h2;
    h1 = md5([username, challenge.realm, password].join(':'));
    h2 = md5(['GET', path].join(':'));
    return md5([h1, challenge.nonce, '000001', '', 'auth', h2].join(':'));
  },
  renderDigest: function(challenge, username, password, path) {
    var params, parts;
    params = {
      username: username,
      realm: challenge.realm,
      nonce: challenge.nonce,
      uri: path,
      qop: challenge.qop,
      response: digest.renderResponse(challenge, username, password, path),
      nc: '000001',
      cnonce: '',
      opaque: challenge.opaque
    };
    parts = _.map(_.keys(params), function(key) {
      return "" + key + "=\"" + params[key] + "\"";
    });
    return 'Digest ' + parts.join(', ');
  }
};
